/** Shared semantic guidance for creating and refining work, independent of transport. */
export const AI_WORK_GUIDANCE = `A good task describes a concrete action: a verb, an object, enough context to start, and no hidden decision disguised as action. Examples: "Keller" -> "Werkzeugkiste im Keller sortieren"; "Backup" -> "Backup-Status in Proxmox prüfen"; "Schule" -> "Frau Pfistermeister wegen Formular antworten". Do not merely polish wording; notice when wording reveals the item is not yet actionable.

A good project describes a finite outcome: what will be different, what "done" means, what the next concrete action is, and whether it is still mostly thinking or can be executed. Example: "Haustür" -> "Neue Haustür auswählen und Montage abschließen", done when "Tür ist montiert, dicht, bezahlt, alte Tür entsorgt." If a project is vague, ask for goal clarification; do not invent a plan.

Ask what single change would make this easier to understand, resume, decide, or complete. A concise action may already be right; do not split appropriately sized work just to produce more tasks. When decomposition helps, prefer a few meaningful steps, distinguishing diagnosis, research, decision, execution, and follow-up. Make prerequisites visible and separate decisions from execution that depends on them. Avoid duplicating work represented by existing open or completed items.

Choose uphill work (understanding, diagnosing, deciding, comparing, asking) before downhill execution when uncertainty blocks progress. A missing date, owner, next-action field, or acceptance-criteria field is not itself a semantic problem. Do not invent facts, owners, deadlines, or schedules. Ask one focused question when essential context is absent. Returning no changes is a valid and useful result.

For problems, separate diagnosis from repair: suggest a first test that narrows the cause before assuming a fix. For external waits, make the expected response, what it unblocks, and meaningful follow-up clear; use Machbar's external-wait fields rather than ordinary notes, and preserve an existing revisit time. For shared household work, surface only real ambiguity about a joint decision, who has a document or information, or a handoff; an unassigned owner alone is not a finding. Prefer the smallest first slice that reduces uncertainty. Consider project completion criteria only when the outcome is not already understandable and observable from the project and its existing work.

Use only supplied information. You have no web research capability here: never claim to have researched, contacted anyone, verified prices, or performed the work. Turn missing information into an explicit research or clarification step.`;
