import { de, taskStatusLabels, stuckReasonLabels } from "@machbar/shared";

/**
 * Every visible string in the app must come from here (or from the shared
 * `de` table). `de` holds the contracts owned by the root package; `extra`
 * covers everything apps/web needs beyond that shared vocabulary. Keeping a
 * single merged `t` object means components never inline literal German
 * text, so the whole UI stays translatable from one place.
 */
const extra = {
  reopen: "Wieder öffnen",
  newProject: "Neues Projekt",
  back: "Zurück",
  close: "Schließen",
  edit: "Bearbeiten",
  delete: "Löschen",
  confirmDeleteTitle: "Wirklich löschen?",
  confirmDeleteBody: "Dieser Vorgang kann nicht rückgängig gemacht werden.",
  yes: "Ja",
  no: "Nein",
  members: "Personen",
  continueAs: "Weiter als",
  switchIdentity: "Person wechseln",
  loading: "Lädt …",
  error: "Etwas ist schiefgelaufen.",
  retry: "Erneut versuchen",
  searchPlaceholder: "Titel, Notizen, Kontext …",
  filters: "Filter",
  resetFilters: "Filter zurücksetzen",
  applyFilters: "Anwenden",
  allMembers: "Alle Personen",
  allProjects: "Alle Projekte",
  allStatuses: "Alle Status",
  anyContext: "Beliebiger Kontext",
  dueFrom: "Fällig von",
  dueTo: "Fällig bis",
  scheduledFrom: "Geplant von",
  scheduledTo: "Geplant bis",
  stuckProjects: "Festgefahrene Projekte",
  repairAction: "Reparaturvorschlag",
  openTasks: "Offen",
  doneTasks: "Erledigt",
  addProject: "Projekt anlegen",
  projectTitle: "Projekttitel",
  description: "Beschreibung",
  noProjects: "Keine Projekte vorhanden.",
  noTasks: "Keine Aufgaben vorhanden.",
  markToday: "Für heute markieren",
  unmarkToday: "Nicht mehr für heute",
  addTag: "Tag hinzufügen",
  removeTag: "Entfernen",
  excludeInheritedTag: "Ausschließen",
  includeInheritedTag: "Ausschluss aufheben",
  excludedTagsTitle: "Ausgeschlossene geerbte Tags",
  addDependency: "Abhängigkeit hinzufügen",
  removeDependency: "Entfernen",
  resolved: "Erledigt",
  unresolved: "Offen",
  organizeMode: "Sortiermodus",
  exitOrganizeMode: "Fertig",
  longPressHint: "Lange drücken zum Sortieren",
  swipeHintComplete: "Nach rechts wischen: erledigen",
  swipeHintDelete: "Nach links wischen: verwerfen",
  selectParent: "Übergeordnete Aufgabe wählen",
  selectProject: "Projekt wählen",
  noParent: "Keine (oberste Ebene)",
  projectLevel: "Projekt-Ebene",
  refile: "Ablegen",
  collapse: "Einklappen",
  expand: "Ausklappen",
  taskDetails: "Details",
  created: "Erstellt",
  updated: "Aktualisiert",
  reminder: "Erinnerung",
  recurrence: "Wiederholung",
  title: "Titel",
  newTask: "Neue Aufgabe",
  quickAddPlaceholder: "Was ist zu tun?",
  clarifyNow: "Jetzt klären",
  clarifyEmpty: "Der Eingang ist leer. Gute Arbeit!",
  waitingEmpty: "Nichts wartet gerade.",
  todayEmpty: "Für heute ist nichts geplant.",
  searchEmpty: "Keine Treffer für diese Suche.",
  moreTitle: "Mehr",
  about: "Über Machbar",
  none: "Keine",
  member: "Person",
  unassigned: "Niemand zugewiesen",
  project: "Projekt",
  noProject: "Kein Projekt",
  taskCompleted: "Aufgabe erledigt",
  taskReopened: "Aufgabe wieder geöffnet",
  openChildrenPrompt: "Wie soll mit den Teilaufgaben verfahren werden?",
  onlyThisTaskCancel: "Nur diese Aufgabe verwerfen",
  addChild: "Teilaufgabe hinzufügen",
  moveHere: "Hierher verschieben",
  organizeControls: "Sortier-Werkzeuge",
  subtreeHint: "Verschiebt die Aufgabe inklusive aller Teilaufgaben.",
  changeParentTitle: "Neue übergeordnete Aufgabe",
  moveProjectTitle: "In anderes Projekt verschieben",
  currentParent: "Aktuell übergeordnet",
  currentProject: "Aktuelles Projekt",
  blockedHint: "Diese Aufgabe kann erst gestartet werden, wenn alle Abhängigkeiten erledigt sind.",
  effectiveTags: "Wirksame Tags",
  ownTags: "Eigene Tags",
  saveChanges: "Änderungen speichern",
  identityRequiredTitle: "Bitte wähle deine Identität",
  identityRequiredBody: "Machbar merkt sich, wer du bist, damit Zuständigkeiten und die Heute-Ansicht stimmen.",
  installApp: "Als App installieren",
  version: "Version",
  followUpFor: "Wartet auf",
  ownContext: "Eigenen Kontext setzen",
  noInheritance: "Keine Vererbung",
  addChildTitle: "Neue Teilaufgabe",
  deleteTaskConfirm: "Aufgabe endgültig löschen?",
  markedTodayLabel: "Heute erledigen",
  waitingForPlaceholder: "z. B. Antwort von Steuerberater",
  contextPlaceholder: "z. B. Zuhause, Büro, Telefon",
  noDependencies: "Keine Abhängigkeiten.",
  noTags: "Keine Tags.",
  searchDependency: "Aufgabe suchen …",
  addTaskToProject: "Aufgabe im Projekt anlegen",
} as const;

export const strings = { ...de, ...extra };
export { taskStatusLabels, stuckReasonLabels };
export type Strings = typeof strings;
