import { de, taskStatusLabels, stuckReasonLabels, projectStatusLabels } from "@machbar/shared";
import type { StuckReason } from "@machbar/shared";
import type { PrimarySwipeAction } from "./swipeSettings";

/**
 * Every visible string in the app must come from here (or from the shared
 * `de` table). `de` holds the contracts owned by the root package; `extra`
 * covers everything apps/web needs beyond that shared vocabulary. Keeping a
 * single merged `t` object means components never inline literal German
 * text, so the whole UI stays translatable from one place.
 */
const extra = {
  reopen: "Wieder öffnen",
  newProject: "Neues Projekt",
  back: "Zurück",
  close: "Schließen",
  edit: "Bearbeiten",
  delete: "Löschen",
  confirmDeleteTitle: "Wirklich löschen?",
  confirmDeleteBody: "Dieser Vorgang kann nicht rückgängig gemacht werden.",
  yes: "Ja",
  no: "Nein",
  members: "Personen",
  continueAs: "Weiter als",
  switchIdentity: "Person wechseln",
  signInTitle: "Bei Machbar anmelden",
  signInBody: "Melde dich mit deinem Pocket-ID-Konto an.",
  signInWithPocketId: "Mit Pocket ID anmelden",
  logout: "Abmelden",
  identityManagedByPocketId:
    "Deine Identität und dein Name werden von Pocket ID verwaltet.",
  pocketIdManaged: "Pocket ID",
  loading: "Lädt …",
  error: "Etwas ist schiefgelaufen.",
  retry: "Erneut versuchen",
  pageHints: "Hinweise",
  showPageHints: "Hinweise zu dieser Seite anzeigen",
  hidePageHints: "Hinweise zu dieser Seite ausblenden",
  searchPlaceholder: "Titel, Notizen, Kontext …",
  filters: "Filter",
  resetFilters: "Filter zurücksetzen",
  applyFilters: "Anwenden",
  allMembers: "Alle Personen",
  allProjects: "Alle Projekte",
  allStatuses: "Alle Status",
  anyContext: "Beliebiger Kontext",
  dueFrom: "Fällig von",
  dueTo: "Fällig bis",
  scheduledFrom: "Geplant von",
  scheduledTo: "Geplant bis",
  stuckProjects: "Festgefahrene Projekte",
  repairAction: "Reparaturvorschlag",
  stuckProjectHeading: "Dieses Projekt ist festgefahren",
  stuckRepairLabels: {
    no_next_action:
      "Lege einen nächsten Schritt fest: Wische eine Aufgabe im Eingang nach rechts, um sie als Machbar zu markieren.",
    only_waiting_without_followup:
      "Setze eine Wiedervorlage oder plane einen eigenen nächsten Schritt.",
    followup_due:
      "Hake jetzt nach oder markiere eine wartende Aufgabe wieder als machbar.",
    blocked_dependencies:
      "Kläre das Ende der Abhängigkeitskette, damit eine Aufgabe machbar wird.",
    unassigned_actionable: "Weise die offene machbare Aufgabe einer Person zu.",
    completion_review: "Prüfe das Ergebnis und schließe das Projekt ab oder ergänze die noch fehlende Arbeit.",
  } satisfies Record<StuckReason, string>,
  openTasks: "Offen",
  doneTasks: "Erledigt",
  addProject: "Projekt anlegen",
  projectTitle: "Projekttitel",
  noProjects: "Keine Projekte vorhanden.",
  noTasks: "Keine Aufgaben vorhanden.",
  addTag: "Tag hinzufügen",
  newTag: "Neuer Tag",
  newTagPlaceholder: "Tag-Name …",
  createTag: "Anlegen",
  createTagHint: "Name und Typ festlegen. Beides kann später geändert werden.",
  tagName: "Tag-Name",
  newTagType: "Typ des neuen Tags",
  editTag: "Tag bearbeiten",
  editTagType: "Tag-Typ bearbeiten",
  searchTags: "Tags durchsuchen",
  searchTagsPlaceholder: "Tag-Name suchen …",
  tagCatalogueEmpty: "Noch keine Tags vorhanden.",
  noMatchingTags: "Keine Tags passen zur Suche.",
  noTagsOfType: "Noch keine Tags dieses Typs.",
  tagKind: "Tag-Typ",
  tagKindLabels: {
    area: "Bereich",
    actor: "Person",
    context: "Kontext",
    plain: "Normal",
  },
  tagGroupingMode: "Gruppierung",
  tagGroupingModeLabels: {
    auto: "Auto",
    pinned: "Angeheftet",
    hidden: "Ausgeblendet",
  },
  noArea: "Ohne Bereich",
  noContext: "Ohne Kontext",
  noActor: "Ohne Person",
  withoutTagKindLabels: {
    area: "Ohne Bereich",
    actor: "Ohne Person",
    context: "Ohne Kontext",
  },
  groupByTagType: "Gruppieren nach",
  noGrouping: "Keine Gruppierung",
  groupingPreference: "Gruppierung",
  groupingPreferenceHint:
    "Bevorzugte Tags werden zuerst als Gruppen verwendet und können priorisiert werden.",
  standardGrouping: "Standard",
  preferredForGrouping: "Beim Gruppieren bevorzugen",
  increaseTagPriority: "Priorität erhöhen",
  decreaseTagPriority: "Priorität senken",
  priorityUp: "Höher",
  priorityDown: "Tiefer",
  allAreas: "Alle Bereiche",
  allActors: "Alle Personen/Stellen",
  moveTagUp: "Tag nach oben",
  moveTagDown: "Tag nach unten",
  manageTags: "Tags verwalten",
  manageTagsHint: "Tag-Katalog, Typen und Gruppierung bearbeiten.",
  manageTagsPageHint:
    "Tags strukturieren Projekte und Aufgaben. Lege passende Typen fest und bestimme, welche Tags beim Gruppieren bevorzugt werden.",
  tagDeleteConfirm: (name: string) =>
    `Tag „${name}“ endgültig löschen? Er wird aus allen Projekten und Aufgaben entfernt.`,
  deleteTag: "Tag löschen",
  deleteTagTitle: (name: string) => `Tag „${name}“ löschen?`,
  deleteTagWarning:
    "Der Tag wird aus allen Projekten und Aufgaben entfernt. Dieser Vorgang kann nicht rückgängig gemacht werden.",
  removeTag: "Entfernen",
  excludeInheritedTag: "Ausschließen",
  includeInheritedTag: "Ausschluss aufheben",
  excludedTagsTitle: "Ausgeschlossene geerbte Tags",
  addDependency: "Abhängigkeit hinzufügen",
  removeDependency: "Entfernen",
  resolved: "Erledigt",
  unresolved: "Offen",
  exitOrganizeMode: "Fertig",
  /**
   * Drag editing replaced the old global organize mode: there is no
   * "Sortiermodus" toggle and no control panel under every row any more —
   * one handle per row, one insertion line, one selected-task toolbar.
   */
  moveTask: "Verschieben",
  dragHint: "Griff ziehen oder lange drücken: Aufgabe verschieben",
  moveFailed: "Verschieben fehlgeschlagen",
  dropTopLevel: "Auf oberste Ebene",
  dropUnder: "Unter",
  dropPosition: "Position",
  swipeHintComplete: "Nach rechts wischen: erledigen",
  swipeHintDelete: "Nach links wischen: verwerfen",
  selectParent: "Übergeordnete Aufgabe wählen",
  selectProject: "Projekt wählen",
  noParent: "Keine (oberste Ebene)",
  projectLevel: "Projekt-Ebene",
  refile: "Ablegen",
  collapse: "Einklappen",
  expand: "Ausklappen",
  taskDetails: "Details",
  created: "Erstellt",
  updated: "Aktualisiert",
  reminder: "Erinnerung",
  recurrence: "Wiederholung",
  title: "Titel",
  newTask: "Neue Aufgabe",
  quickAddPlaceholder: "Was ist zu tun?",
  captureMachbar: "Machbar",
  captureMachbarHint: "Erscheint sofort in Heute",
  captureProject: "Projekt",
  captureProjectHint: "In Schritte zerlegen",
  clarifyLater: "Später klären",
  filedInInbox: "In Eingang abgelegt",
  addedToToday: "In Heute hinzugefügt",
  changeOwner: "Zuständig ändern",
  undo: "Rückgängig",
  projectBreakdownTitle: "Projekt weiterdenken",
  nextStepQuestion: "Was ist der nächste Schritt?",
  addNextAction: "Nächsten Schritt hinzufügen",
  waitingItem: "Wartepunkt",
  addWaitingItem: "Wartepunkt hinzufügen",
  saveNotes: "Notizen speichern",
  finishLater: "Später fertig machen",
  clarifyNow: "Jetzt klären",
  needsClarification: "Zu klären",
  clarifyEmpty: "Der Eingang ist leer. Gute Arbeit!",
  waitingEmpty: "Nichts wartet gerade.",
  todayEmpty: "Für heute ist nichts geplant.",
  searchEmpty: "Keine Treffer für diese Suche.",
  moreTitle: "Mehr",
  about: "Über Machbar",
  none: "Keine",
  member: "Person",
  me: "Ich",
  sharedOwner: "Gemeinsam",
  unassigned: "Niemand zugewiesen",
  project: "Projekt",
  noProject: "Kein Projekt",
  taskCompleted: "Aufgabe erledigt",
  taskReopened: "Aufgabe wieder geöffnet",
  openChildrenPrompt: "Wie soll mit den Teilaufgaben verfahren werden?",
  onlyThisTaskCancel: "Nur diese Aufgabe verwerfen",
  addChild: "Teilaufgabe hinzufügen",
  moveHere: "Hierher verschieben",
  organizeControls: "Sortier-Werkzeuge",
  subtreeHint: "Verschiebt die Aufgabe inklusive aller Teilaufgaben.",
  changeParentTitle: "Neue übergeordnete Aufgabe",
  moveProjectTitle: "In anderes Projekt verschieben",
  currentParent: "Aktuell übergeordnet",
  currentProject: "Aktuelles Projekt",
  searchDestination: "Ziel suchen",
  searchDestinationPlaceholder: "Projekt oder Aufgabe suchen …",
  recentDestinations: "Zuletzt verwendet",
  allDestinations: "Alle Ziele",
  destinationSearchEmpty: "Kein Ziel passt zu dieser Suche.",
  blockedHint: "Diese Aufgabe kann erst gestartet werden, wenn alle Abhängigkeiten erledigt sind.",
  effectiveTags: "Wirksame Tags",
  taskTags: "Tags",
  moreTaskTags: (count: number) => `${count} weitere Tags`,
  ownTags: "Eigene Tags",
  saveChanges: "Änderungen speichern",
  saveNext: "Speichern & weiter",
  identityRequiredTitle: "Bitte wähle deine Identität",
  identityRequiredBody: "Machbar merkt sich, wer du bist, damit Zuständigkeiten und die Heute-Ansicht stimmen.",
  firstMemberHint: "Noch ist niemand angelegt. Erstelle die erste Person, um Machbar zu starten.",
  installApp: "Als App installieren",
  version: "Version",
  followUpFor: "Wartet auf",
  revisitDate: "Wiedervorlage",
  newRevisitDate: "Neue Wiedervorlage",
  unknownMember: "Unbekannte Person",
  ownContext: "Eigenen Kontext setzen",
  noInheritance: "Keine Vererbung",
  ownerInheritanceParent: "Übergeordnet",
  ownerInheritanceTaskSpecific: "Aufgabenspezifisch",
  ownerInheritanceNone: "Keine",
  addChildTitle: "Neue Teilaufgabe",
  addSuccessor: "Nächsten Schritt danach hinzufügen",
  successorPlaceholder: "Nächster Schritt",
  addSequence: "Ablauf hinzufügen",
  sequenceSteps: "Schritte in Reihenfolge",
  sequencePlaceholder:
    "Angebot einholen\nTermin vereinbaren\nArbeit abnehmen\nRechnung bezahlen",
  sequenceHint:
    "Eine Zeile pro Schritt. Jeder spätere Schritt wartet auf den vorherigen.",
  addSequenceCount: (count: number) =>
    count < 2 ? "Mindestens zwei Schritte" : `${count} Schritte hinzufügen`,
  deleteTaskConfirm: "Aufgabe endgültig löschen?",
  deleteProject: "Projekt löschen",
  deleteProjectConfirm:
    "Projekt endgültig löschen? Die Aufgaben bleiben erhalten und werden keinem Projekt mehr zugeordnet.",
  waitingForPlaceholder: "z. B. Antwort von Steuerberater",
  contextPlaceholder: "z. B. Zuhause, Büro, Telefon",
  noDependencies: "Keine Abhängigkeiten.",
  noTags: "Keine Tags.",
  searchDependency: "Aufgabe suchen …",
  addTaskToProject: "Aufgabe im Projekt anlegen",
  todayExplanation:
    "Diese Übersicht wird automatisch aus Terminen, Fälligkeiten und dem Status berechnet – ohne manuelle Markierung.",
  manageMembers: "Personen verwalten",
  manageMembersHint: "Lege Personen an, benenne sie um oder entferne sie.",
  memberName: "Name",
  editMemberName: "Name bearbeiten",
  memberNamePlaceholder: "z. B. Mira",
  addMember: "Person hinzufügen",
  renameMember: "Umbenennen",
  memberDeleteConfirm: "Person endgültig löschen?",
  noMembers: "Noch keine Personen angelegt.",
  swipeSettingTitle: "Wischgeste",
  swipeSettingHint:
    "Bestimmt, was ein Wisch nach rechts in Aufgabenlisten auslöst. Nach links wischen zeigt immer Zuweisen, Planen, Notizen sowie Warten/Mehr. Bereits erledigte oder verworfene Aufgaben werden durch die Wischgeste immer wieder geöffnet.",
  swipeHintChips: "Nach links wischen oder ⋯: Zuweisen, Planen, Notizen, Zum Projekt, Warten, Mehr",
  taskGestures: "Aufgaben bedienen",
  taskGestureHint: (rightAction: string) =>
    `Nach rechts wischen: „${rightAction}“. Nach links wischen öffnet weitere Aktionen wie Zuweisen, Planen und Notizen. Am Desktop geht das auch über ⋯.`,
  assign: "Zuweisen",
  schedule: "Planen",
  scheduleShortcuts: "Schnell planen",
  scheduleShortcutLabels: {
    unscheduled: "Nicht geplant",
    today: "Heute",
    tomorrow: "Morgen",
    nextWeek: "Nächste Woche",
    weekend: "Wochenende",
  },
  moreActions: "Weitere Aktionen",
  toProject: "Zum Projekt",
  noProjectChipHint: "Kein Projekt zugeordnet",
  assignProject: "Projekt zuweisen",
  primarySwipeActionLabels: {
    complete: "Erledigen / Wieder öffnen",
    waiting: "Warten",
    someday: "Irgendwann",
    cancel: "Verwerfen",
  } satisfies Record<PrimarySwipeAction, string>,
  refinementMatrixTitle: "Zuständig × Aufwand",
  refinementMatrixHint: "Sekundäre Übersicht: Zeile oder Spalte antippen, um nach Zuständigkeit und Aufwand zu filtern.",
  refinementListTitle: "Offene Aufgaben nach Aufwand",
  unestimated: "Ohne Aufwand",
  total: "Gesamt",
  allSizes: "Jeder Aufwand",
  clearSize: "Aufwand entfernen",
  story: "Projekt",
  task: "Aufgabe",
  currentSize: "Aufwand",
  swipeHintSize: "Nach rechts wischen: Aufwand weiterschalten (S → M → L → XL → ohne)",
  swipeHintSizeChips: "Nach links wischen oder ⋯: Aufwand direkt wählen, Zuweisen, Zum Projekt",
  refinementEmpty: "Keine offenen Aufgaben in dieser Übersicht.",
  resetFilter: "Filter zurücksetzen",
  filteredBy: "Gefiltert nach",

  clarificationNeeds: "Klärungsbedarf",
  clarificationNeedsHint: "Diese Dinge brauchen Klärung. Behebe jeweils den nächsten konkreten Punkt.",
  clarificationNeedsEmpty: "Gerade gibt es keinen Klärungsbedarf.",
  effortGuide: "Aufwand",
  effortGuideHint: "S = kurzer Handgriff · M = normale Aufgabe · L = längerer Block · XL = zu groß",

  // --- Project clarification -------------------------------------------
  backlogReview: "Projektklärung",
  refinement: "Aufgabenklärung",
  backlogReviewHint: "Noch nicht aktive Projekte prüfen, gezielt ergänzen und erst dann aktiv machen.",
  backlogReviewEmpty: "Keine Projekte unter „Später / noch nicht aktiv“.",
  activateStory: "Aktiv machen",
  driver: "Verantwortlich",
  assignDriver: "Verantwortliche Person zuweisen",
  assignDriverToActivateHint: "Für die Aktivierung muss zuerst eine verantwortliche Person zugewiesen werden.",
  driverLockedHint:
    "Die verantwortliche Person kann erst entfernt werden, wenn das Projekt wieder auf „Später / noch nicht aktiv“ steht.",
  noDriver: "Niemand zugewiesen",
  criteria: "Erledigt, wenn …",
  planDates: "Planen",
  planDatesTitle: "Termine planen",
  taskSummary: "Aufgaben",
  taskSummaryNone: "Noch keine Aufgaben",
  archiveStory: "Archivieren",
  storyActivated: "Aktiv gemacht",
  storyArchived: "Archiviert",
  storyCompleted: "Abgeschlossen",
  storyReopened: "Wieder geöffnet",
  storyReturnedToBacklog: "Auf später verschoben",

  // --- Projects tab (Projekte) -----------------------------------------
  projectsSwipeHint:
    "Nach rechts wischen führt den nächsten Workflow-Schritt aus, nach links wischen oder ⋯ zeigt weitere Aktionen.",
  projectStatus: "Status",
  workflowStep: "Workflow-Schritt",
  projectSearchPlaceholder: "Titel, Notizen oder „Erledigt, wenn …“ suchen …",
  projectScopeMineOpen: "Meine & offen",
  projectScopeAll: "Alle",
  noMatchingProjects: "Keine Projekte für Suche/Filter.",
  finishedProjectsSection: (count: number) => `Abgeschlossen & archiviert (${count})`,

  // --- Project/story detail editing (Projekte › Detail › Bearbeiten) ---
  openProject: "Projekt öffnen",
  editProject: "Projekt bearbeiten",
  returnToBacklogStory: "Auf später verschieben",
  completeStory: "Abschließen",
  lifecycleActions: "Workflow-Aktionen",
  taskProgress: "Aufgaben",
  addCriterion: "Punkt hinzufügen",
  addCriterionPlaceholder: "Erledigt, wenn …",
  removeCriterion: "Kriterium entfernen",
  moveCriterionUp: "Kriterium nach oben",
  moveCriterionDown: "Kriterium nach unten",
  noCriteria: "Noch nicht festgelegt, wann das Projekt erledigt ist.",
  projectAgenda: "Projekte",
  projectReview: "Projekt prüfen",
  projectDue: "Projekt fällig",
  projectReviewAndDue: "Projekt prüfen & fällig",
  review: "Prüfen",
  shareWithMachbar: "Mit Machbar teilen",
  noSharedContent: "Es wurde kein Inhalt zum Teilen übergeben.",
  toMachbar: "Zu Machbar",
  createNew: "Neu anlegen",
  searchShareTargets: "Aufgaben und Projekte durchsuchen",
  sharing: "Wird hinzugefügt …",
  sharedWith: (title: string) => `Zu „${title}“ hinzugefügt`,
  openSharedTarget: "Ziel öffnen",
  share: "Teilen",
  shareCompleted: "Geteilt",
  copiedToClipboard: "In die Zwischenablage kopiert",
  clipboardUnavailable: "Teilen und Zwischenablage sind nicht verfügbar.",
  markdownToolbar: "Markdown formatieren",
  markdownBulletList: "Aufzählung",
  markdownTaskList: "Checkbox",
  markdownBold: "Fett",
  markdownLink: "Link einfügen",
  editNotes: "Notizen bearbeiten",
  noNotes: "Noch keine Notizen.",
} as const;

export const strings = { ...de, ...extra };
export { taskStatusLabels, stuckReasonLabels, projectStatusLabels };
export type Strings = typeof strings;
