import { de, taskStatusLabels, stuckReasonLabels, projectStatusLabels } from "@machbar/shared";
import type { PrimarySwipeAction } from "./swipeSettings";

/**
 * Every visible string in the app must come from here (or from the shared
 * `de` table). `de` holds the contracts owned by the root package; `extra`
 * covers everything apps/web needs beyond that shared vocabulary. Keeping a
 * single merged `t` object means components never inline literal German
 * text, so the whole UI stays translatable from one place.
 */
const extra = {
  reopen: "Wieder öffnen",
  newProject: "Neues Projekt",
  back: "Zurück",
  close: "Schließen",
  edit: "Bearbeiten",
  delete: "Löschen",
  confirmDeleteTitle: "Wirklich löschen?",
  confirmDeleteBody: "Dieser Vorgang kann nicht rückgängig gemacht werden.",
  yes: "Ja",
  no: "Nein",
  members: "Personen",
  continueAs: "Weiter als",
  switchIdentity: "Person wechseln",
  loading: "Lädt …",
  error: "Etwas ist schiefgelaufen.",
  retry: "Erneut versuchen",
  searchPlaceholder: "Titel, Notizen, Kontext …",
  filters: "Filter",
  resetFilters: "Filter zurücksetzen",
  applyFilters: "Anwenden",
  allMembers: "Alle Personen",
  allProjects: "Alle Projekte",
  allStatuses: "Alle Status",
  anyContext: "Beliebiger Kontext",
  dueFrom: "Fällig von",
  dueTo: "Fällig bis",
  scheduledFrom: "Geplant von",
  scheduledTo: "Geplant bis",
  stuckProjects: "Festgefahrene Projekte",
  repairAction: "Reparaturvorschlag",
  openTasks: "Offen",
  doneTasks: "Erledigt",
  addProject: "Projekt anlegen",
  projectTitle: "Projekttitel",
  noProjects: "Keine Projekte vorhanden.",
  noTasks: "Keine Aufgaben vorhanden.",
  addTag: "Tag hinzufügen",
  removeTag: "Entfernen",
  excludeInheritedTag: "Ausschließen",
  includeInheritedTag: "Ausschluss aufheben",
  excludedTagsTitle: "Ausgeschlossene geerbte Tags",
  addDependency: "Abhängigkeit hinzufügen",
  removeDependency: "Entfernen",
  resolved: "Erledigt",
  unresolved: "Offen",
  organizeMode: "Sortiermodus",
  exitOrganizeMode: "Fertig",
  longPressHint: "Lange drücken zum Sortieren",
  swipeHintComplete: "Nach rechts wischen: erledigen",
  swipeHintDelete: "Nach links wischen: verwerfen",
  selectParent: "Übergeordnete Aufgabe wählen",
  selectProject: "Projekt wählen",
  noParent: "Keine (oberste Ebene)",
  projectLevel: "Projekt-Ebene",
  refile: "Ablegen",
  collapse: "Einklappen",
  expand: "Ausklappen",
  taskDetails: "Details",
  created: "Erstellt",
  updated: "Aktualisiert",
  reminder: "Erinnerung",
  recurrence: "Wiederholung",
  title: "Titel",
  newTask: "Neue Aufgabe",
  quickAddPlaceholder: "Was ist zu tun?",
  clarifyNow: "Jetzt klären",
  clarifyEmpty: "Der Eingang ist leer. Gute Arbeit!",
  waitingEmpty: "Nichts wartet gerade.",
  todayEmpty: "Für heute ist nichts geplant.",
  searchEmpty: "Keine Treffer für diese Suche.",
  moreTitle: "Mehr",
  about: "Über Machbar",
  none: "Keine",
  member: "Person",
  unassigned: "Niemand zugewiesen",
  project: "Projekt",
  noProject: "Kein Projekt",
  taskCompleted: "Aufgabe erledigt",
  taskReopened: "Aufgabe wieder geöffnet",
  openChildrenPrompt: "Wie soll mit den Teilaufgaben verfahren werden?",
  onlyThisTaskCancel: "Nur diese Aufgabe verwerfen",
  addChild: "Teilaufgabe hinzufügen",
  moveHere: "Hierher verschieben",
  organizeControls: "Sortier-Werkzeuge",
  subtreeHint: "Verschiebt die Aufgabe inklusive aller Teilaufgaben.",
  changeParentTitle: "Neue übergeordnete Aufgabe",
  moveProjectTitle: "In anderes Projekt verschieben",
  currentParent: "Aktuell übergeordnet",
  currentProject: "Aktuelles Projekt",
  searchDestination: "Ziel suchen",
  searchDestinationPlaceholder: "Projekt oder Aufgabe suchen …",
  recentDestinations: "Zuletzt verwendet",
  allDestinations: "Alle Ziele",
  destinationSearchEmpty: "Kein Ziel passt zu dieser Suche.",
  blockedHint: "Diese Aufgabe kann erst gestartet werden, wenn alle Abhängigkeiten erledigt sind.",
  effectiveTags: "Wirksame Tags",
  ownTags: "Eigene Tags",
  saveChanges: "Änderungen speichern",
  identityRequiredTitle: "Bitte wähle deine Identität",
  identityRequiredBody: "Machbar merkt sich, wer du bist, damit Zuständigkeiten und die Heute-Ansicht stimmen.",
  installApp: "Als App installieren",
  version: "Version",
  followUpFor: "Wartet auf",
  newRevisitDate: "Neue Wiedervorlage",
  unknownMember: "Unbekannte Person",
  ownContext: "Eigenen Kontext setzen",
  noInheritance: "Keine Vererbung",
  addChildTitle: "Neue Teilaufgabe",
  deleteTaskConfirm: "Aufgabe endgültig löschen?",
  waitingForPlaceholder: "z. B. Antwort von Steuerberater",
  contextPlaceholder: "z. B. Zuhause, Büro, Telefon",
  noDependencies: "Keine Abhängigkeiten.",
  noTags: "Keine Tags.",
  searchDependency: "Aufgabe suchen …",
  addTaskToProject: "Aufgabe im Projekt anlegen",
  todayExplanation:
    "Diese Übersicht wird automatisch aus Terminen, Fälligkeiten und dem Status berechnet – ohne manuelle Markierung.",
  manageMembers: "Personen verwalten",
  manageMembersHint: "Lege Personen an, benenne sie um oder entferne sie.",
  memberName: "Name",
  editMemberName: "Name bearbeiten",
  memberNamePlaceholder: "z. B. Mira",
  addMember: "Person hinzufügen",
  renameMember: "Umbenennen",
  memberDeleteConfirm: "Person endgültig löschen?",
  noMembers: "Noch keine Personen angelegt.",
  swipeSettingTitle: "Wischgeste",
  swipeSettingHint:
    "Bestimmt, was ein Wisch nach rechts in Aufgabenlisten auslöst. Nach links wischen zeigt immer Zuweisen, Planen, Notizen sowie Warten/Mehr. Bereits erledigte oder verworfene Aufgaben werden durch die Wischgeste immer wieder geöffnet.",
  swipeHintChips: "Nach links wischen oder ⋯: Zuweisen, Planen, Notizen, Zum Projekt, Warten, Mehr",
  assign: "Zuweisen",
  schedule: "Planen",
  moreActions: "Weitere Aktionen",
  toProject: "Zum Projekt",
  noProjectChipHint: "Kein Projekt zugeordnet",
  primarySwipeActionLabels: {
    complete: "Erledigen / Wieder öffnen",
    waiting: "Warten",
    someday: "Irgendwann",
    cancel: "Verwerfen",
  } satisfies Record<PrimarySwipeAction, string>,
  refinementMatrixTitle: "Zuständig × Größe",
  refinementMatrixHint: "Zeile oder Spalte antippen, um die Liste unten zu filtern.",
  refinementListTitle: "Offene Aufgaben zur Verfeinerung",
  unestimated: "Ohne Schätzung",
  total: "Gesamt",
  allSizes: "Alle Größen",
  clearSize: "Schätzung entfernen",
  story: "Story",
  currentSize: "Aktuelle Größe",
  swipeHintSize: "Nach rechts wischen: Größe weiterschalten (S → M → L → XL → ohne)",
  swipeHintSizeChips: "Nach links wischen oder ⋯: Größe direkt wählen, Zuweisen, Zum Projekt",
  refinementEmpty: "Keine offenen Aufgaben zur Verfeinerung.",
  resetFilter: "Filter zurücksetzen",
  filteredBy: "Gefiltert nach",

  // --- Backlog review (Mehr › Backlog prüfen) --------------------------
  backlogReview: "Backlog prüfen",
  refinement: "Refinement",
  backlogReviewHint: "Nach rechts wischen aktiviert eine Geschichte, nach links wischen oder ⋯ zeigt weitere Aktionen.",
  backlogReviewEmpty: "Keine Geschichten im Backlog.",
  activateStory: "Aktivieren",
  driver: "Verantwortlich",
  assignDriver: "Verantwortliche Person zuweisen",
  assignDriverToActivateHint: "Für die Aktivierung muss zuerst eine verantwortliche Person zugewiesen werden.",
  driverLockedHint:
    "Die verantwortliche Person kann erst entfernt werden, wenn die Geschichte wieder im Backlog liegt.",
  noDriver: "Niemand zugewiesen",
  criteria: "Akzeptanzkriterien",
  planDates: "Planen",
  planDatesTitle: "Termine planen",
  taskSummary: "Aufgaben",
  taskSummaryNone: "Noch keine Aufgaben",
  archiveStory: "Archivieren",
  storyActivated: "Aktiviert",
  storyArchived: "Archiviert",
  storyCompleted: "Abgeschlossen",
  storyReopened: "Wieder geöffnet",
  storyReturnedToBacklog: "Zurück im Backlog",

  // --- Projects tab (Projekte) -----------------------------------------
  projectsSwipeHint:
    "Nach rechts wischen führt den nächsten Workflow-Schritt aus, nach links wischen oder ⋯ zeigt weitere Aktionen.",
  projectStatus: "Status",
  workflowStep: "Workflow-Schritt",

  // --- Project/story detail editing (Projekte › Detail › Bearbeiten) ---
  editProject: "Projekt bearbeiten",
  returnToBacklogStory: "In Backlog zurücklegen",
  completeStory: "Abschließen",
  lifecycleActions: "Workflow-Aktionen",
  taskProgress: "Aufgaben",
  addCriterion: "Kriterium hinzufügen",
  addCriterionPlaceholder: "Neues Akzeptanzkriterium",
  removeCriterion: "Kriterium entfernen",
  moveCriterionUp: "Kriterium nach oben",
  moveCriterionDown: "Kriterium nach unten",
  noCriteria: "Noch keine Akzeptanzkriterien.",
} as const;

export const strings = { ...de, ...extra };
export { taskStatusLabels, stuckReasonLabels, projectStatusLabels };
export type Strings = typeof strings;
